repos:
  # ------------------------
  # Lua formatting & linting
  # ------------------------
  - repo: https://github.com/JohnnyMorganz/stylua
    rev: v2.3.0  # Use latest stable version
    hooks:
      - id: stylua
        files: \.lua$
        args: ["--config-path", ".stylua.toml"]  # Optional: if you have a stylua config

  # ------------------------
  # Markdown linting
  # ------------------------
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint
        files: \.md$

  # ------------------------
  # YAML linting
  # ------------------------
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: \.(yml|yaml)$
